### ISSUE TITLE
画图程序

### ISSUE THREAD

**Issue by phyzhangyang** [phyzhangyang/EasyScan_HEP#23]
在图中直接反映出限制先后的样本点
在画图之前，判断要画图的数据是否是常数或者非数字，如果是，就跳过该图片并提醒用户

**Comment by shangliang** [comment]
Easyscan中方法用的是小写字母单词+大写字母单词+大写字母单词+
成员用的是大写字母单词+大写字母单词+大写字母单词+
方法命名首单词体现动态，成员命名而体现静态。

**Comment by shangliang** [comment]
对常数和非数字进行了判断

**Comment by shangliang** [comment]
Scatter方法中生成了Compare_*.png图片，含有限制前后的数据。
