### ISSUE TITLE
程序运行的方式

### ISSUE THREAD

**Issue by phyzhangyang** [phyzhangyang/EasyScan_HEP#24]
目前用python调用其他程序有两种方式，subprocess和os
有些程序不用通过subprocess或者os调用。所以两种方式都要提供，默认使用subprocess（或os），然后在[scan]中添加一个选择。

**Comment by shangliang** [comment]
这个我没有看懂呀，有些程序不用通过subprocess或者os，指的是既不通过subprocess和os，还是必须用其中的一个？

**Comment by shangliang** [comment]
另外，在【scan】中添加选择，指的是默认subprocess或os的选择吗？

**Comment by shangliang** [comment]
我认为，subprocess或os的具体选择不是应该在[programX]中进行选择吗？

**Comment by phyzhangyang** [comment]
是，在program中选择。
我的意思是让用户选择是用os还是subprocess。
还有其他选择么？另外，如果考虑到未来的并行，是哪个好？

**Comment by shangliang** [comment]
是不是不用这两种方式的区别？如果是一般用户，可能就不懂os和subprocess的区别。

**Comment by shangliang** [comment]
如果不用，可以close

**Comment by phyzhangyang** [comment]
在program section添加了一个新选项：Command executor，可以设置为os.system或者subprocess.Popen。默认是os.system
