### ISSUE TITLE
运行外部软件前删除输出文件

### ISSUE THREAD

**Issue by phyzhangyang** [phyzhangyang/EasyScan_HEP#25]
运行外部软件时，删除对应的输出文件。原因是如果不删除，有可能该软件没有正确输出，也就是非物理点，但输出文件存在，就会被错误读取。
之前这个功能缺失，但是通过下面方法避免了
[program1]

Program name:    susyhit-1.6

Execute command:  rm susyhit_slha.out

                  ./run

Command path:    ../Externals/susyhit/

也就是当中的 rm susyhit_slha.out

**Comment by yuanfangtardis** [comment]
good point！

**Comment by shangliang** [comment]
通过RemoveOutputFile实现了此功能。
