### ISSUE TITLE
constrain中指导构建chi 2的量，可以是计算表达式

### ISSUE THREAD

**Issue by shangliang** [phyzhangyang/EasyScan_HEP#26]
在做dampe工作时，要求暗物质和传播子的质量差小于5个GeV。
根据这个具体的需求，对程序要求有相应的功能。

**Comment by phyzhangyang** [comment]
对，这个需要。我的建议是设计成
[constraint]
Gaussian:        omg,    0.1199,    0.012
Bound：            x,         1,      5                        # x在[1,5]范围内
Bound：            x,         upper,      5                        # x<5
Bound：            x,         lower,      1                        # x>1
Bounds:           mn1, omg, upper, /home/someone/lux.dat  # lux.dat中是两列数据，通过插值的方法，要求所有点在这两列描述的排除线之下

**Comment by shangliang** [comment]
这里的bound已经处理好了

**Comment by shangliang** [comment]
这里的bounds已经处理好了

**Comment by shangliang** [comment]
Bounds和Bound在Program里加，如果不满足要求直接从新点开始。这样设计的好处是：
如果spheno比如，算出来的结果mh=130，加上bound<128直接扔掉了。
如果把这个bound加到constrain里，这个点还需要算micomegas等。
