### ISSUE TITLE
SUSYHIT无法使用SLHA输入模式

### ISSUE THREAD

**Issue by phyzhangyang** [phyzhangyang/EasyScan_HEP#31]
SLHA输入模式下，被改变的行前面没有空格。这样的输入文件在SUSYHIT中无法使用

**Comment by shangliang** [comment]
bin/read_mc.ini中Input parametes应该是Input parameters

**Comment by shangliang** [comment]
被改变的行前面不仅添加了空格，并且保留了原始空格数目！
