### ISSUE TITLE
math 方法的简化

### ISSUE THREAD

**Issue by phyzhangyang** [phyzhangyang/EasyScan_HEP#34]
programX中的input参数，默认前面都有一个math，这样就不用特别说明了

**Comment by shangliang** [comment]
把init.py中parseMath函数替换为以下即可！

**Comment by shangliang** [comment]
def parseMath(par):
    ## Thanks to authors at the web page http://lybniz2.sourceforge.net/safeeval.html

    from math import *
    ## make a list of safe functions
    safe_list = ['math','acos', 'asin', 'atan', 'atan2', 'ceil', 'cos', 'cosh',
                 'degrees', 'e', 'exp', 'fabs', 'floor', 'fmod', 'frexp', 'hypot',
                 'ldexp', 'log', 'log10', 'modf', 'pi', 'pow', 'radians', 'sin',
                 'sinh', 'sqrt', 'tan', 'tanh']

    ## use the list to filter the local namespace
    safe_dict = dict([ (k, locals().get(k, None)) for k in safe_list ])
    ## add any needed builtins back in.
    safe_dict['abs'] = abs
    safe_dict['float'] = float

    safe_dict.update(par)
    safe_dict.update({"__builtins__": None})

    for key,value in par.items():
        expr = ','.join(key.split(':'))

        try:
            cal = eval(expr, safe_dict)
        except SyntaxError:
            for keyAlt,valueAlt in par.items():
                if type(valueAlt) == str:
                    expr=expr.replace(keyAlt, valueAlt)
                else:
                    if isnan(valueAlt):
                        expr=expr.replace(keyAlt, "float('NaN')")
                    else:
                        expr=expr.replace(keyAlt, str(valueAlt))
            cal = eval(expr, safe_dict)

        #print key, expr, cal; raw_input("math") 
        par[key] = cal

**Comment by phyzhangyang** [comment]
鹏轩的文章改起来比想象中难很多，现在还没有开始弄ES


-----Original Messages-----

**Comment by shangliang** [comment]
def parseMath(par):
    ## Thanks to authors at the web page http://lybniz2.sourceforge.net/safeeval.html

    from math import *
    ## make a list of safe functions
    safe_list = ['math','acos', 'asin', 'atan', 'atan2', 'ceil', 'cos', 'cosh',
                 'degrees', 'e', 'exp', 'fabs', 'floor', 'fmod', 'frexp', 'hypot',
                 'ldexp', 'log', 'log10', 'modf', 'pi', 'pow', 'radians', 'sin',
                 'sinh', 'sqrt', 'tan', 'tanh']

    ## use the list to filter the local namespace
    safe_dict = dict([ (k, locals().get(k, None)) for k in safe_list ])
    ## add any needed builtins back in.
    safe_dict['abs'] = abs
    safe_dict['float'] = float

    safe_dict.update(par)
    safe_dict.update({"__builtins__": None})

    for key,value in par.items():
        expr = ','.join(key.split(':'))

        try:
            cal = eval(expr, safe_dict)
        except SyntaxError:
            for keyAlt,valueAlt in par.items():
                if type(valueAlt) == str:
                    expr=expr.replace(keyAlt, valueAlt)
                else:
                    if isnan(valueAlt):
                        expr=expr.replace(keyAlt, "float('NaN')")
                    else:
                        expr=expr.replace(keyAlt, str(valueAlt))
            cal = eval(expr, safe_dict)

        #print key, expr, cal; raw_input("math") 
        par[key] = cal

**Comment by shangliang** [comment]
把init.py中parseMath函数替换为以下即可！

**Comment by shangliang** [comment]
def parseMath(par):
## Thanks to authors at the web page http://lybniz2.sourceforge.net/safeeval.html

from math import *
## make a list of safe functions
safe_list = ['math','acos', 'asin', 'atan', 'atan2', 'ceil', 'cos', 'cosh',
             'degrees', 'e', 'exp', 'fabs', 'floor', 'fmod', 'frexp', 'hypot',
             'ldexp', 'log', 'log10', 'modf', 'pi', 'pow', 'radians', 'sin',
             'sinh', 'sqrt', 'tan', 'tanh']

## use the list to filter the local namespace
safe_dict = dict([ (k, locals().get(k, None)) for k in safe_list ])
## add any needed builtins back in.
safe_dict['abs'] = abs
safe_dict['float'] = float

safe_dict.update(par)
safe_dict.update({"__builtins__": None})

for key,value in par.items():
    expr = ','.join(key.split(':'))

    try:
        cal = eval(expr, safe_dict)
    except SyntaxError:
        for keyAlt,valueAlt in par.items():
            if type(valueAlt) == str:
                expr=expr.replace(keyAlt, valueAlt)
            else:
                if isnan(valueAlt):
                    expr=expr.replace(keyAlt, "float('NaN')")
                else:
                    expr=expr.replace(keyAlt, str(valueAlt))
        cal = eval(expr, safe_dict)

    #print key, expr, cal; raw_input("math") 
    par[key] = cal

**Comment by shangliang** [comment]
def parseMath(par):
## Thanks to authors at the web page http://lybniz2.sourceforge.net/safeeval.html

from math import *
## make a list of safe functions
safe_list = ['math','acos', 'asin', 'atan', 'atan2', 'ceil', 'cos', 'cosh',
             'degrees', 'e', 'exp', 'fabs', 'floor', 'fmod', 'frexp', 'hypot',
             'ldexp', 'log', 'log10', 'modf', 'pi', 'pow', 'radians', 'sin',
             'sinh', 'sqrt', 'tan', 'tanh']

## use the list to filter the local namespace
safe_dict = dict([ (k, locals().get(k, None)) for k in safe_list ])
## add any needed builtins back in.
safe_dict['abs'] = abs
safe_dict['float'] = float

safe_dict.update(par)
safe_dict.update({"__builtins__": None})

for key,value in par.items():
    expr = ','.join(key.split(':'))

    try:
        cal = eval(expr, safe_dict)
    except SyntaxError:
        for keyAlt,valueAlt in par.items():
            if type(valueAlt) == str:
                expr=expr.replace(keyAlt, valueAlt)
            else:
                if isnan(valueAlt):
                    expr=expr.replace(keyAlt, "float('NaN')")
                else:
                    expr=expr.replace(keyAlt, str(valueAlt))
        cal = eval(expr, safe_dict)

    #print key, expr, cal; raw_input("math") 
    par[key] = cal

**Comment by shangliang** [comment]
def parseMath(par):
    ## Thanks to authors at the web page http://lybniz2.sourceforge.net/safeeval.html

    from math import *
    ## make a list of safe functions
    safe_list = ['math','acos', 'asin', 'atan', 'atan2', 'ceil', 'cos', 'cosh',
                 'degrees', 'e', 'exp', 'fabs', 'floor', 'fmod', 'frexp', 'hypot',
                 'ldexp', 'log', 'log10', 'modf', 'pi', 'pow', 'radians', 'sin',
                 'sinh', 'sqrt', 'tan', 'tanh']

    ## use the list to filter the local namespace
    safe_dict = dict([ (k, locals().get(k, None)) for k in safe_list ])
    ## add any needed builtins back in.
    safe_dict['abs'] = abs
    safe_dict['float'] = float

    safe_dict.update(par)
    safe_dict.update({"__builtins__": None})

    for key,value in par.items():
        expr = ','.join(key.split(':'))

        try:
            cal = eval(expr, safe_dict)
        except SyntaxError:
            for keyAlt,valueAlt in par.items():
                if type(valueAlt) == str:
                    expr=expr.replace(keyAlt, valueAlt)
                else:
                    if isnan(valueAlt):
                        expr=expr.replace(keyAlt, "float('NaN')")
                    else:
                        expr=expr.replace(keyAlt, str(valueAlt))
            cal = eval(expr, safe_dict)

        #print key, expr, cal; raw_input("math") 
        par[key] = cal
