### ISSUE TITLE
在ini中实现简单计算

### ISSUE THREAD

**Issue by phyzhangyang** [phyzhangyang/EasyScan_HEP#4]
添加一种Input variable功能：

Input variable:  mu,   1, Replace,  ES_mu
                        m1,   1, Replace,  ES_m1
                          c,    1, Calculate, "par['m1']^2"

实现方法：
ss="par['mh1']^2"
cc="c"
eval("par["+cc+"]="+ss)

不确定是不是”par“

**Comment by shangliang** [comment]
关于c,1,Calculate,"par["m1"]^2"
其实需要两步实现：
c,1,Calculate,"par["m1"]^2"
c,1,Replace,ES_c

**Comment by phyzhangyang** [comment]
Input和output都要有这个功能

**Comment by phyzhangyang** [comment]
python中对应的命令势exec，不是eval

**Comment by shangliang** [comment]
在这个功能的时候，修改了mainfun.py中re.sub条件，使得ES_lam in ES_lamT 不会被替换。

**Comment by shangliang** [comment]
在这个功能的时候，把文件中所有的typo：wihch -> which.

**Comment by shangliang** [comment]
在实现这个功能的同时，简化了判断机制，在setInputVar和WriteInputFile中，如果满足前者的判断，自然满足后者的判断。因此，去掉了后者的判断。

**Comment by shangliang** [comment]
在实现这个功能的同时，对于setInputVar的中postion等方法的输入检查独立成了函数

**Comment by shangliang** [comment]
在这个功能的时候，把文件中所有的typo：lable -> label.

**Comment by shangliang** [comment]
在这个功能的时候，把文件中所有的typo：labl* -> label*

**Comment by shangliang** [comment]
无论在input variable和output variable，label 只能出现一行匹配，并且label后边的关键字区分大小写。

**Comment by shangliang** [comment]
在setInputVar中对position, label, slha, file（file是部分代码）被分解了出来，因为这个部分也要用到setoutvar中，避免代码写两次。

**Comment by shangliang** [comment]
slha的检查做了改进：key用逗号隔开（之前应该是用空格分开的），比如
zh11, 1, slha, block, zh, 1, 1
这样做的目的是与position部分的写法保持一致。

**Comment by shangliang** [comment]
slha的检查做了改进：增加了注释，主要是我在理解代码时，发现有“难度”的代码进行了解释。

**Comment by shangliang** [comment]
slha的检查做了改进：debug, erorstop, info等的输出做了改进，比如slha data line->slha match data line，因为我们这里呈现的是匹配结果，所以增加了match。

**Comment by shangliang** [comment]
去掉了WriteInputFile中对输入的检查，因为已经在setInputVar中完成。

**Comment by shangliang** [comment]
WriteInputFile中SLHA方法bug修复，正确的代码为：
if jj[3].upper() == kk[0].upper()

**Comment by shangliang** [comment]
WriteInputFile中SLHA方法bug修复，正确的代码为：
                       if jj[3].upper() == 'DECAY' and jj[5] == 0:
                            invar[kki][2]=str(par[jj[0]])
                            ks_flag  = True
                            break

**Comment by shangliang** [comment]
修改了我见到的代码中类似open    (    ->   open( 书写不规范的问题

**Comment by shangliang** [comment]
修复了replace方法，检查输入和文件内容是否匹配时，特殊情况会遇到的bug。主要是对re.sub和re.findall的利用，其中用\b，可以避免如下错误匹配，
lam_s 匹配到 las_st中

**Comment by shangliang** [comment]
修复了replace方法，检查输入和文件内容是否匹配时，特殊情况会遇到的bug。主要是对re.sub和re.findall的利用，其中用\b，可以避免如下错误匹配，
lam_s 匹配到 lam_st中

**Comment by shangliang** [comment]
input file增加了判断，确保不能有相同的file ID。

**Comment by shangliang** [comment]
在mainfun.py中优化了  file_flag 的含义，如果file_flag为true，表示文件是用户自己编写的，而file_flag为false，表示文件是之前程序产生的。对于后者，无需检查其格式。
因为目前的程序框架是，在程序运行之前，既需要setInputVar，此函数对input file进行检测，而程序运行之前一般不会存在程序产生的文件。因此无法对程序产生的文件进行检测。

**Comment by shangliang** [comment]
程序中所有的typo: parametes -> parameters

**Comment by shangliang** [comment]
插曲：在算checkmate v1时，如果用其中计算s95的函数，那么
numpy.__version__
1.11.0
scipy.__version__
0.17.0

pip install numpy==1.11.0可以实现

**Comment by shangliang** [comment]
sf.WarningWait( 'For the scan method you choosed, o     nly 6 items ( ID, Prior distribution, Minimum, Maximum, Step width, Initial      value) are needed for each input parameter. But the parameter [%s] has %i      items. The last %i will be ignored.'%(ii[0],lenii,5-lenii) )
这里，lenii是大于5的，所以应该是lenii-5

**Comment by shangliang** [comment]
sf.WarningWait( 'For the scan method you choosed, o nly 6 items ( ID, Prior distribution, Minimum, Maximum, Step width, Initial value) are needed for each input parameter. But the parameter [%s] has %i items. The last %i will be ignored.'%(ii[0],lenii,5-lenii) )
这里，lenii是大于5的，所以应该是lenii-5。

**Comment by shangliang** [comment]
print '* For the scan method you choosed, the items of      each input parameter should include at least 2 items ( ID, Value). But the      paramter [%s] missed %i of them.'%(ii[0],2-lenii)
                      exit(1)
                  elif lenii > 2:
                      print '# Warning: For the scan method you choosed, only      2 items ( ID, Value) are needed for each input parameter. But the paramete     r [%s] has %i items. The last %i will be ignored.'%(ii[0],linii,2-lenii)
这里：
第一个print改为errorstop
第二个print改为warningwait
linii->lenii
最后一行2-lenii->lenii-2
这样的小改动不再记录啦。

**Comment by shangliang** [comment]
整体上，代码的注释稳步增多，可读性进一步增强。但是这些注释也存在随机性，因为它们只是在我阅读我感兴趣的代码时，对我觉得有“难度”的地方进行了解释。

**Comment by shangliang** [comment]
终于实现了这个功能，相关的说明已经写到了说明书中。
