### ISSUE TITLE
unphysical points

### ISSUE THREAD

**Issue by shangliang** [phyzhangyang/EasyScan_HEP#43]
关于扫描时得到的非物理点（不论何种扫描方式都有可能遇到）
处理方式：
1. 保留
2. 不保留
如果保留：
单独输出一个文件，只保留输入参数。（相应的ScanInf.txt也需要产生？）

另外，
对于我们加入Bound，例如Bound： mh > 123 and mh < 125。
不满足Bound的点，计入“unboundphysical points”（另外一个输入文件）

**Comment by phyzhangyang** [comment]
目前是不保留
