### ISSUE TITLE
[program]里面Bound:好像有点问题。

### ISSUE THREAD

**Issue by wk-mike** [phyzhangyang/EasyScan_HEP#44]
对参数x  y 进行扫描，在program里面什么都不干，只是复制文件，保证输出文件都一样。
[program1]
Bound:  x,     y,     lower,   utils/bound_wk.in
相当于是在x  y平面上加了一条排除线。可是通过画图x y 感觉不是很对。
需要修改program.py 程序891  /893两行
par[ii[0]] 改为 par[ii[1]]

感觉是将y值跟y的限制值做比较
print('"%s=%f" v.s. "%s=%f" compare to the %s limit "%s=%f" by interplotion in "Bound" for program %s'%(ii[0], par[ii[0]], ii[1], par[ii[1]], ii[2].lower(), ii[1], yinter, self._ProgName))
输出
"x=103.714929" v.s. "y=9952.170002" compare to the lower limit "y=103.714929" by interplotion in "Bound" for program test

所以感觉是【par[ii[1]]】跟【par[jj[4]] = yinter】 进行比较

改之前和之后的图片
![Scatter_x_y-old](https://user-images.githubusercontent.com/19682026/56716046-e5701400-676b-11e9-9e02-01c42b634518.png)
![Scatter_x_y-new](https://user-images.githubusercontent.com/19682026/56716053-eacd5e80-676b-11e9-8c70-6a6bba932307.png)

test.ini文件：
[scan]
Result file name:  first-scan
Scan method:       random
Points number:     1000
Input parameters:  y,   Flat, -10000, 10000 
                   x,   log,   1,     10000  

Random seed:       2
Interval of print: 100

[program1]
Program name:     test
Execute command:    cp  out.wk  out

Command path:    utils/
Input file:      
Input variable:  
Output file: 1,  utils/out
Output variable:  mh1,  1 ,  SLHA,  BLOCK,   MASS,    25

Bound:  x,     y,     lower,   utils/bound_wk.in

[constraint]
Gaussian:        mh1,    125.0,    2.0

[plot]
scatter: x, y

out.wk文件
BLOCK MASS
25  123

bound_wk.in文件
-100  -100
10000  10000

**Comment by shangliang** [comment]
谢谢，我写错了。你说的对，我已经push了新的代码，并且把debug语句写的更清楚了。
