### ISSUE TITLE
Citation for this?

### ISSUE THREAD

**Issue by kratsg** [phyzhangyang/EasyScan_HEP#47]
Is there a preferred citation for this tool? There appears to be no arXiv link and I notice others have cited https://arxiv.org/abs/1612.02296 .

Is it best to do something similar to

> [#] Y. Zhang and L. Shang, EasyScan HEP, July, 2016. [Online] Available at: http://easyscanhep.hepforge.org.

**Comment by phyzhangyang** [comment]
Thanks very much for using ES! Either way is fine.

**Comment by phyzhangyang** [comment]
We have now published our manual on arXiv. A better option would be

@article{Shang:2023gfy,
    author = "Shang, Liangliang and Zhang, Yang",
    title = "{EasyScan\_HEP: a tool for connecting programs to scan the parameter space of physics models}",
    eprint = "2304.03636",
    archivePrefix = "arXiv",
    primaryClass = "hep-ph",
    month = "4",
    year = "2023"
}
