### ISSUE TITLE
不同输入方式的实现

### ISSUE THREAD

**Issue by phyzhangyang** [phyzhangyang/EasyScan_HEP#5]
目前版本中只有Replace可以用，其他的处在问题。

主要是目前版本会把table改为空格，导致有些软件无法读取输入文件。

**Comment by shangliang** [comment]
现在基本上解决了这个问题，并且输出更为好看，只是在做了更改的地方输出与原始文件有差别。
新作更改的行，以\t和两个空格作为字符之间的间隔，基本上兼容所有程序的读取。
不过，不完美的地方就是，做过更改的行，未能保持全貌。
我close comment了，如果后续觉得有问题，可以重开有关这个问题的comment。

**Comment by phyzhangyang** [comment]
这个目前足够了，你push上来了么？
