### ISSUE TITLE
随机数种子

### ISSUE THREAD

**Issue by phyzhangyang** [phyzhangyang/EasyScan_HEP#6]
（不确定，需要check）目前只有在multinest模式下随机数种子有用其他模式没有用

**Comment by shangliang** [comment]
在random，mcmc和Multinest中使用了随机数

**Comment by shangliang** [comment]
对于
random，mcmc和Multinest
三种模式，用户可以提供种子，不提供时发出警告提示。

**Comment by shangliang** [comment]
对于不需要random的运行模式，用户可以不提供random选项。

**Comment by shangliang** [comment]
以上想法已经写成了代码
