### ISSUE TITLE
constraint 必须提供的问题

### ISSUE THREAD

**Issue by phyzhangyang** [phyzhangyang/EasyScan_HEP#9]
目前constraint必须提供。但是对于一些扫描，constraint没有必要，要求用户随便设置一个不太好，还是改程序，把constraint改为可选的比较好

**Comment by shangliang** [comment]
如果没有读到constrain，把chi2设为一个常数，是否能满足上述要求？

**Comment by phyzhangyang** [comment]
可以

**Comment by shangliang** [comment]
对于read，grid和random扫描，配置文件中[constraint]无需提供。
